import type { CatalogItem } from './types'

export const CATALOG: CatalogItem[] = [
  {
    id: 'cafe-chair',
    name: 'Café chair',
    sku: 'CHR-01',
    category: 'restaurant',
    costGroup: 'seating',
    price: 180,
    w: 0.46,
    d: 0.5,
    h: 0.86,
    plan: 'chair',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'stool',
    name: 'Counter stool',
    sku: 'STL-02',
    category: 'restaurant',
    costGroup: 'seating',
    price: 160,
    w: 0.4,
    d: 0.4,
    h: 0.76,
    plan: 'stool',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'table-4',
    name: '4-top table',
    sku: 'TBL-04',
    category: 'restaurant',
    costGroup: 'tables',
    price: 480,
    w: 0.9,
    d: 0.9,
    h: 0.75,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'table-2',
    name: '2-top table',
    sku: 'TBL-02',
    category: 'restaurant',
    costGroup: 'tables',
    price: 320,
    w: 0.7,
    d: 0.7,
    h: 0.75,
    plan: 'round',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'banquette',
    name: 'Banquette 4p',
    sku: 'BAN-04',
    category: 'restaurant',
    costGroup: 'seating',
    price: 900,
    w: 2.2,
    d: 0.68,
    h: 0.92,
    plan: 'banquette',
    blocksCirculation: true,
    isSeat: true,
    seats: 4,
  },
  {
    id: 'espresso-bar',
    name: 'Espresso bar',
    sku: 'BAR-12',
    category: 'restaurant',
    costGroup: 'counters',
    price: 2400,
    w: 3.2,
    d: 0.72,
    h: 1.08,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'service-counter',
    name: 'Service counter',
    sku: 'CTR-18',
    category: 'restaurant',
    costGroup: 'counters',
    price: 1800,
    w: 1.8,
    d: 0.6,
    h: 0.92,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'pendant',
    name: 'Pendant light',
    sku: 'LGT-P1',
    category: 'restaurant',
    costGroup: 'lighting',
    price: 220,
    w: 0.28,
    d: 0.28,
    h: 0.38,
    plan: 'pendant',
    blocksCirculation: false,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'fridge',
    name: 'Display fridge',
    sku: 'FRG-01',
    category: 'restaurant',
    costGroup: 'counters',
    price: 2100,
    w: 0.9,
    d: 0.72,
    h: 2.0,
    plan: 'fridge',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'host-stand',
    name: 'Host stand',
    sku: 'HST-01',
    category: 'restaurant',
    costGroup: 'other',
    price: 640,
    w: 0.55,
    d: 0.5,
    h: 1.12,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'planter',
    name: 'Planter',
    sku: 'PLN-08',
    category: 'restaurant',
    costGroup: 'other',
    price: 180,
    w: 0.42,
    d: 0.42,
    h: 0.95,
    plan: 'round',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'desk',
    name: 'Work desk',
    sku: 'DSK-16',
    category: 'office',
    costGroup: 'tables',
    price: 720,
    w: 1.6,
    d: 0.8,
    h: 0.75,
    plan: 'desk',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'task-chair',
    name: 'Task chair',
    sku: 'CHR-T2',
    category: 'office',
    costGroup: 'seating',
    price: 340,
    w: 0.62,
    d: 0.62,
    h: 1.05,
    plan: 'chair',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'lounge',
    name: 'Lounge sofa',
    sku: 'SOF-02',
    category: 'office',
    costGroup: 'seating',
    price: 1680,
    w: 1.8,
    d: 0.82,
    h: 0.78,
    plan: 'banquette',
    blocksCirculation: true,
    isSeat: true,
    seats: 2,
  },
  {
    id: 'credenza',
    name: 'Credenza',
    sku: 'CRD-18',
    category: 'office',
    costGroup: 'counters',
    price: 980,
    w: 1.8,
    d: 0.45,
    h: 0.74,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'gondola',
    name: 'Gondola bay',
    sku: 'GON-12',
    category: 'retail',
    costGroup: 'counters',
    price: 860,
    w: 1.2,
    d: 0.54,
    h: 1.45,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'checkout',
    name: 'Checkout',
    sku: 'CHK-01',
    category: 'retail',
    costGroup: 'counters',
    price: 1420,
    w: 1.6,
    d: 0.7,
    h: 0.95,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'display-table',
    name: 'Display table',
    sku: 'DSP-09',
    category: 'retail',
    costGroup: 'tables',
    price: 540,
    w: 1.2,
    d: 0.8,
    h: 0.9,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
]

export const CATALOG_BY_ID: Record<string, CatalogItem> = Object.fromEntries(
  CATALOG.map((item) => [item.id, item]),
)

export function catalogItem(id: string): CatalogItem {
  const item = CATALOG_BY_ID[id]
  if (!item) throw new Error(`Unknown catalog item: ${id}`)
  return item
}
