import type { CatalogItem } from './types'

export const CATALOG: CatalogItem[] = [
  {
    id: 'cafe-chair',
    name: 'Café chair',
    sku: 'CHR-01',
    category: 'restaurant',
    costGroup: 'seating',
    price: 180,
    w: 0.46,
    d: 0.5,
    h: 0.86,
    plan: 'chair',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'stool',
    name: 'Counter stool',
    sku: 'STL-02',
    category: 'restaurant',
    costGroup: 'seating',
    price: 160,
    w: 0.4,
    d: 0.4,
    h: 0.76,
    plan: 'stool',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'table-4',
    name: '4-top table',
    sku: 'TBL-04',
    category: 'restaurant',
    costGroup: 'tables',
    price: 480,
    w: 0.9,
    d: 0.9,
    h: 0.75,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'table-2',
    name: '2-top table',
    sku: 'TBL-02',
    category: 'restaurant',
    costGroup: 'tables',
    price: 320,
    w: 0.7,
    d: 0.7,
    h: 0.75,
    plan: 'round',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'banquette',
    name: 'Banquette 4p',
    sku: 'BAN-04',
    category: 'restaurant',
    costGroup: 'seating',
    price: 900,
    w: 2.2,
    d: 0.68,
    h: 0.92,
    plan: 'banquette',
    blocksCirculation: true,
    isSeat: true,
    seats: 4,
  },
  {
    id: 'espresso-bar',
    name: 'Espresso bar',
    sku: 'BAR-12',
    category: 'restaurant',
    costGroup: 'counters',
    price: 2400,
    w: 3.2,
    d: 0.72,
    h: 1.08,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'service-counter',
    name: 'Service counter',
    sku: 'CTR-18',
    category: 'restaurant',
    costGroup: 'counters',
    price: 1800,
    w: 1.8,
    d: 0.6,
    h: 0.92,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'pendant',
    name: 'Pendant light',
    sku: 'LGT-P1',
    category: 'restaurant',
    costGroup: 'lighting',
    price: 220,
    w: 0.28,
    d: 0.28,
    h: 0.38,
    plan: 'pendant',
    blocksCirculation: false,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'fridge',
    name: 'Display fridge',
    sku: 'FRG-01',
    category: 'restaurant',
    costGroup: 'counters',
    price: 2100,
    w: 0.9,
    d: 0.72,
    h: 2.0,
    plan: 'fridge',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'host-stand',
    name: 'Host stand',
    sku: 'HST-01',
    category: 'restaurant',
    costGroup: 'other',
    price: 640,
    w: 0.55,
    d: 0.5,
    h: 1.12,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'planter',
    name: 'Planter',
    sku: 'PLN-08',
    category: 'restaurant',
    costGroup: 'other',
    price: 180,
    w: 0.42,
    d: 0.42,
    h: 0.95,
    plan: 'round',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'desk',
    name: 'Work desk',
    sku: 'DSK-16',
    category: 'office',
    costGroup: 'tables',
    price: 720,
    w: 1.6,
    d: 0.8,
    h: 0.75,
    plan: 'desk',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'task-chair',
    name: 'Task chair',
    sku: 'CHR-T2',
    category: 'office',
    costGroup: 'seating',
    price: 340,
    w: 0.62,
    d: 0.62,
    h: 1.05,
    plan: 'chair',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'lounge',
    name: 'Lounge sofa',
    sku: 'SOF-02',
    category: 'office',
    costGroup: 'seating',
    price: 1680,
    w: 1.8,
    d: 0.82,
    h: 0.78,
    plan: 'banquette',
    blocksCirculation: true,
    isSeat: true,
    seats: 2,
  },
  {
    id: 'credenza',
    name: 'Credenza',
    sku: 'CRD-18',
    category: 'office',
    costGroup: 'counters',
    price: 980,
    w: 1.8,
    d: 0.45,
    h: 0.74,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'gondola',
    name: 'Gondola bay',
    sku: 'GON-12',
    category: 'retail',
    costGroup: 'counters',
    price: 860,
    w: 1.2,
    d: 0.54,
    h: 1.45,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'checkout',
    name: 'Checkout',
    sku: 'CHK-01',
    category: 'retail',
    costGroup: 'counters',
    price: 1420,
    w: 1.6,
    d: 0.7,
    h: 0.95,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'display-table',
    name: 'Display table',
    sku: 'DSP-09',
    category: 'retail',
    costGroup: 'tables',
    price: 540,
    w: 1.2,
    d: 0.8,
    h: 0.9,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'hab-mod',
    name: 'Pressure module',
    sku: 'HAB-04',
    category: 'habitat',
    costGroup: 'habitat',
    price: 48000,
    w: 2.4,
    d: 2.4,
    h: 2.4,
    plan: 'module',
    blocksCirculation: true,
    isSeat: true,
    seats: 2,
  },
  {
    id: 'airlock',
    name: 'Airlock',
    sku: 'ALK-01',
    category: 'habitat',
    costGroup: 'habitat',
    price: 36000,
    w: 1.6,
    d: 1.2,
    h: 2.2,
    plan: 'module',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    sku: 'BIO-12',
    category: 'habitat',
    costGroup: 'life',
    price: 54000,
    w: 3.2,
    d: 1.8,
    h: 2.1,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'eclss',
    name: 'ECLSS rack',
    sku: 'LS-09',
    category: 'habitat',
    costGroup: 'life',
    price: 72000,
    w: 1.2,
    d: 0.8,
    h: 2.0,
    plan: 'fridge',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'solar-array',
    name: 'Solar array',
    sku: 'PWR-20',
    category: 'habitat',
    costGroup: 'power',
    price: 18000,
    w: 3.6,
    d: 1.1,
    h: 0.18,
    plan: 'rect',
    blocksCirculation: false,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'rtg',
    name: 'RTG / nuclear pack',
    sku: 'PWR-N1',
    category: 'habitat',
    costGroup: 'power',
    price: 94000,
    w: 1.0,
    d: 1.0,
    h: 1.4,
    plan: 'round',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'rad-shelter',
    name: 'Storm shelter',
    sku: 'RAD-02',
    category: 'habitat',
    costGroup: 'habitat',
    price: 41000,
    w: 2.2,
    d: 2.2,
    h: 1.6,
    plan: 'module',
    blocksCirculation: true,
    isSeat: true,
    seats: 4,
  },
  {
    id: 'isru',
    name: 'ISRU plant',
    sku: 'ISRU-3',
    category: 'habitat',
    costGroup: 'life',
    price: 88000,
    w: 2.0,
    d: 1.6,
    h: 2.2,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'waiting-chair',
    name: 'Waiting chair',
    sku: 'MED-W1',
    category: 'healthcare',
    costGroup: 'seating',
    price: 220,
    w: 0.52,
    d: 0.56,
    h: 0.84,
    plan: 'chair',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'exam-table',
    name: 'Exam table',
    sku: 'MED-X2',
    category: 'healthcare',
    costGroup: 'tables',
    price: 1860,
    w: 1.9,
    d: 0.7,
    h: 0.8,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: true,
    seats: 1,
  },
  {
    id: 'reception',
    name: 'Reception desk',
    sku: 'MED-R1',
    category: 'healthcare',
    costGroup: 'counters',
    price: 2400,
    w: 2.4,
    d: 0.7,
    h: 1.1,
    plan: 'bar',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'sofa',
    name: 'Sofa',
    sku: 'HOM-S3',
    category: 'home',
    costGroup: 'seating',
    price: 2200,
    w: 2.2,
    d: 0.9,
    h: 0.82,
    plan: 'banquette',
    blocksCirculation: true,
    isSeat: true,
    seats: 3,
  },
  {
    id: 'coffee-table',
    name: 'Coffee table',
    sku: 'HOM-C1',
    category: 'home',
    costGroup: 'tables',
    price: 480,
    w: 1.2,
    d: 0.6,
    h: 0.4,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'bed',
    name: 'Queen bed',
    sku: 'HOM-B1',
    category: 'home',
    costGroup: 'other',
    price: 1600,
    w: 1.6,
    d: 2.1,
    h: 0.55,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'nightstand',
    name: 'Nightstand',
    sku: 'HOM-N1',
    category: 'home',
    costGroup: 'other',
    price: 280,
    w: 0.5,
    d: 0.4,
    h: 0.55,
    plan: 'rect',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'student-desk',
    name: 'Student desk',
    sku: 'EDU-D1',
    category: 'education',
    costGroup: 'tables',
    price: 260,
    w: 0.7,
    d: 0.5,
    h: 0.74,
    plan: 'desk',
    blocksCirculation: true,
    isSeat: false,
    seats: 0,
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    sku: 'EDU-W1',
    category: 'education',
    costGroup: 'other',
    price: 420,
    w: 2.4,
    d: 0.08,
    h: 1.2,
    plan: 'bar',
    blocksCirculation: false,
    isSeat: false,
    seats: 0,
  },
]

export const CATALOG_BY_ID: Record<string, CatalogItem> = Object.fromEntries(
  CATALOG.map((item) => [item.id, item]),
)

export function catalogItem(id: string): CatalogItem {
  const item = CATALOG_BY_ID[id]
  if (!item) throw new Error(`Unknown catalog item: ${id}`)
  return item
}
